# Header

menu:
  主页: /
  #随笔: /tags/随笔/

# SubNav
subnav:
  github: "https://github.com/cczeng"
  #weibo: "http://weibo.com/p/1005055213009629/home?from=page_100505&mod=TAB&is_all=1#place"
  #rss: "#"
  zhihu: "https://www.zhihu.com/people/ceng-liang-97/activities"
  qq: "http://wpa.qq.com/msgrd?v=3&uin=1501725626&site=qq&menu=yes"
  #weixin: "#"
  #jianshu: "#"
  #douban: "#"
  #segmentfault: "#"
  #bilibili: "#"
  #acfun: "#"
  mail: "mailto:cc501725626@gmail.com"
  #facebook: "#"
  #google: "#"
  twitter: "https://twitter.com/"
  #linkedin: "#"

rss: /atom.xml

# 是否需要修改 root 路径
# 如果您的网站存放在子目录中，例如 http://yoursite.com/blog，
# 请将您的 url 设为 http://yoursite.com/blog 并把 root 设为 /blog/。
root: 

# Content

# 文章太长，截断按钮文字
excerpt_link: 
# 文章卡片右下角常驻链接，不需要请设置为false
show_all_link: '展开全文'
# 数学公式
mathjax: false
# 是否在新窗口打开链接
open_in_new: false

# 打赏
# 请在需要打赏的文章的md文件头部，设置属性reward: true

# 打赏基础设定：0-关闭打赏； 1-文章对应的md文件里有reward:true属性，才有打赏； 2-所有文章均有打赏
reward_type: 2
# 打赏wording
reward_wording: '感谢您的支持,我会继续努力'
# 支付宝二维码图片地址，跟你设置头像的方式一样。比如：/assets/img/alipay.jpg
alipay: /img/alipay.png
# 微信二维码图片地址
weixin: /img/wechat.png

# Miscellaneous
baidu_analytics: ''
google_analytics: ''
favicon: /favicon.png

#你的头像url
avatar: /img/head.jpg

#是否开启分享
share_jia: true

#评论：1、多说；2、网易云跟帖；3、畅言；4、Disqus 不需要使用某项，直接设置值为false，或注释掉
#具体请参考wiki：https://github.com/litten/hexo-theme-yilia/wiki/

#1、多说
duoshuo: false

#2、网易云跟帖
wangyiyun: fd9aceff07134e4f9c230333725250f0

#3、畅言
changyan_appid: false
changyan_conf: false

#4、Disqus 在hexo根目录的config里也有disqus_shortname字段，优先使用yilia的
disqus: false

# 样式定制 - 一般不需要修改，除非有很强的定制欲望…
style:
  # 头像上面的背景颜色
  header: '#4d4d4d'
  # 右滑板块背景
  slider: 'linear-gradient(200deg,#a0cfe4,#e8c37e)'

# slider的设置
slider:
  # 是否默认展开tags板块
  showTags: true

#是否开启访客数量统计功能
counter: true

# 智能菜单
# 如不需要，将该对应项置为false
# 比如
#smart_menu:
#  friends: false
smart_menu:
  innerArchive: '所有文章'
  friends: '友链'
  aboutme: '关于我'

friends:
  我的班级网站: http://zengliang.site/
  创客空间——环院工作室: http://zlfai.com/
  Tinypng(在线图片压缩): https://tinypng.com/

aboutme: 曾亮<br>就读于江西环境工程职业学院<br><br>
        爱骑行,<br>爱生活,<br>爱自己<br><br>
        生活不只是眼前的苟且,<br>还有诗和远方.